# Generated by Django 6.0.5 on 2026-05-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('queixa', models.CharField(choices=[('D', 'Depressao'), ('A', 'Ansiedade')], max_length=1)),
            ],
        ),
    ]
